project:
  type: website
  output-dir: _site
  title: Julian Dehne
  render:
    - "*.qmd"
    - "!publications/"
    - "!applications/"

website:
  title: "Julian Dehne"
  description: "Julian's Academic Website"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "Current Work"
        href: current.qmd
      - text: "CV"
        href: cv_old.qmd
      - text: "CV Download"
        href: cv.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Academic Progress"
        href: achievements.qmd
      - text: "Software"
        href: software.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "About Me"
        href: about.qmd

format:
  html:
    theme: lux
    css: styles.css

execute:
  enabled: true
  echo: false
  warning: false
  error: false
  cache: false
  r-path: "C:/Program Files/R/R-4.4.0/bin/x64/R"
  python-path: "C:/ProgramData/anaconda3/envs/sem_rep_left-right/bin/python"
  freeze: auto

author:
  - name: Julian Dehne
    orcid: 0000-0001-9265-9619
    email: julian.dehne@gi.de
    url: https://juliandehne.github.io
    affiliations:
      - name: Gesellschaft für Informatik
        address: Weydingerstraße 14-16, 10178 Berlin
      - name: University of Potsdam
        address: An der Bahn 2,  14476 Potsdam

profile:
  default: website
